## Generate recent red/blue heat maps for Brazil and Colombia in stacked panels
## with quantiles for significant red and blues.
## These plots require the m-files generated in "06-generate-m-files.R" and values 
## generated by the permutation test in "06-permutation-test-HPC.R".
## We provide sample data generated from our models in the Materials folder.
## This file also contains code for plotting SI Figures 4-6.

setwd("~/dengue-Zika-chik_Americas")
source("Scripts/04-generateBiweeks.R")
source("Scripts/04-getLocationAttributes.R")
load("lat_values.Rdata")
source("Scripts/set_location_order_colors.R")

library(dplyr)
#library(tidyr)
library(ggplot2)
library(grid)
library(gridExtra)

## function for counting biweeks with higher than expected dengue incicence
above.signif <- function(m.dat){
  by(
    m.dat
    ,factor(m.dat$biweekEndDate)
    , function(temp.dat){
      num.above=sum(temp.dat$significant==1, na.rm=T)
    })
}

## function for counting biweeks with lower than expected dengue incicence
below.signif <- function(m.dat){
  by(
    m.dat
    ,factor(m.dat$biweekEndDate)
    , function(temp.dat){
      num.above=sum(temp.dat$significant==-1, na.rm=T)
    })
}

## get Brazil quantiles and red/blue data frame
country.choice="Brazil"
attCountry <- get(paste0('att',country.choice))

load("Materials/incidenceDat_Brazil.Rdata")
load("Materials/permute_Brazil.Rdata")
load("Materials/permutationTest_Brazil.Rdata")

use.m=permute.m
use.m$pindex = -attCountry$getPindexFromLocation(use.m$location)

num.states=length(unique(use.m$location))

use.m$test.colors[which((use.m$observed<use.m$`5%`)&(use.m$observed>=use.m$`2.5%`))]=rgb(0,0,1,0.4)
use.m$test.colors[which((use.m$observed>use.m$`95%`)&(use.m$observed<=use.m$`97.5%`))]=rgb(1,0,0,0.4)


use.m$p.vals.bonferroni=p.adjust(use.m$p.vals,method="bonferroni") #use.m$p.vals
unique(use.m$p.vals.bonferroni)
use.m$p.vals.adjust=.9
use.m$p.vals.adjust[which(use.m$p.vals.bonferroni<.05)]=.6
use.m$p.vals.adjust[which(use.m$p.vals.bonferroni<.025)]=0

use.m$test.colors.adjust[which(use.m$quantile>.5)]=rgb(1,0,0,alpha=1-use.m$p.vals.adjust[which(use.m$quantile>.5)])
use.m$test.colors.adjust[which(use.m$quantile<=.5)]=rgb(0,0,1,alpha=1-use.m$p.vals.adjust[which(use.m$quantile<=.5)])

signif.above=as.numeric(above.signif(use.m))
signif.below=as.numeric(below.signif(use.m))

top.bar1=subset(use.m,location==use.m$location[1])
top.bar1$location=""
top.bar1$test.colors=rgb(1,0,0,alpha=signif.above/num.states)

top.bar2=subset(use.m,location==use.m$location[1])
top.bar2$location=""
top.bar2$test.colors=rgb(0,0,1,alpha=signif.below/num.states)

top.bar1$pindex=4  
top.bar2$pindex=3  

Brazil.m=rbind(top.bar1,top.bar2,use.m)
Brazil.full.m=use.m


## get Colombia quantiles and red/blue data frame
country.choice="Colombia"
attCountry <- get(paste0('att',country.choice))

load("Materials/incidenceDat_Colombia.Rdata")
load("Materials/permute_Colombia.Rdata")
load("Materials/permutationTest_Colombia.Rdata")

use.m=permute.m

use.m$pindex = -attCountry$getPindexFromLocation(use.m$location)

use.m$test.colors[which((use.m$observed<use.m$`5%`)&(use.m$observed>=use.m$`2.5%`))]=rgb(0,0,1,0.4)
use.m$test.colors[which((use.m$observed>use.m$`95%`)&(use.m$observed<=use.m$`97.5%`))]=rgb(1,0,0,0.4)

use.m$p.vals.bonferroni=p.adjust(use.m$p.vals,method="bonferroni")
unique(use.m$p.vals.bonferroni)
use.m$p.vals.adjust=.9
use.m$p.vals.adjust[which(use.m$p.vals.bonferroni<.05)]=.6
use.m$p.vals.adjust[which(use.m$p.vals.bonferroni<.025)]=0

use.m$test.colors.adjust[which(use.m$quantile>.5)]=rgb(1,0,0,alpha=1-use.m$p.vals.adjust[which(use.m$quantile>.5)])
use.m$test.colors.adjust[which(use.m$quantile<=.5)]=rgb(0,0,1,alpha=1-use.m$p.vals.adjust[which(use.m$quantile<=.5)])

num.states=length(unique(use.m$location))

signif.above=as.numeric(above.signif(use.m))
signif.below=as.numeric(below.signif(use.m))

top.bar1=subset(use.m,location==use.m$location[1])
top.bar1$location=""
top.bar1$test.colors=rgb(1,0,0,alpha=signif.above/num.states)

top.bar2=subset(use.m,location==use.m$location[1])
top.bar2$location=""
top.bar2$test.colors=rgb(0,0,1,alpha=signif.below/num.states)

top.bar1$pindex=4  
top.bar2$pindex=3  

Colombia.m=rbind(top.bar1,top.bar2,use.m)
Colombia.full.m=use.m


# update Colombia.m pindex so the rows are after Brazil.m
Colombia.m$pindex=Colombia.m$pindex+min(Brazil.m$pindex)-10
Colombia.full.m$pindex=Colombia.full.m$pindex+min(Brazil.full.m$pindex)-5

temp.m=rbind(Brazil.m,Colombia.m)
temp.full.m=rbind(Brazil.full.m,Colombia.full.m)

plot.recent=T
if(plot.recent==T){
  m=subset(temp.m,year>2013)
}else{
  m=temp.full.m
}
# get date boundaries and labels
time.start=min(as.Date(m$biweekEndDate))
time.end=max(as.Date(m$biweekEndDate))+7

# These breaks are most appropriate for recent years only plots 
# since forcing 26 biweeks in each year for model pushes some biweeks into adjacent years
temp.breaks=c()
for(temp.year in unique(m$year)){
  temp.dat=subset(m,year==temp.year)
  temp.breaks=c(temp.breaks,as.character(temp.dat$biweekEndDate[1]))
}
temp.breaks=as.Date(temp.breaks)-7
label.years=as.integer(substr(as.character(temp.breaks), 1,4))
temp.breaks=c(temp.breaks,time.end)
label.years=c(label.years,"")
x.year=temp.breaks+365/2

margin.info=T

start.x = as.Date(time.start-8)
end.x = as.Date(time.end+1)
start.y = max(m$pindex[which(m$pindex <0)] )+0.5
end.y = min(m$pindex)-0.5

y1=unique(subset(m,location=="Rio_Grande_do_Sul")$pindex)-0.5
y2=unique(subset(m,location=="San_Andres")$pindex)+0.5

B.blue.labels=paste0(Brazil.signif.blues," (q=",signif(Brazil.blue.q.vals,digits=3)[(length(Brazil.blue.q.vals)-3):length(Brazil.blue.q.vals)],"%)")
B.red.labels=paste0(Brazil.signif.reds," (q=",signif(Brazil.red.q.vals,digits=3)[(length(Brazil.red.q.vals)-3):length(Brazil.red.q.vals)]*100,"%)")

if(plot.recent==T){
  Brazil.blue.vals=Brazil.blue.q.vals[(length(Brazil.blue.q.vals)-3):length(Brazil.blue.q.vals)]
  Brazil.red.vals=Brazil.red.q.vals[(length(Brazil.red.q.vals)-3):length(Brazil.red.q.vals)]
  Colombia.blue.vals=Colombia.blue.q.vals[(length(Colombia.blue.q.vals)-3):length(Colombia.blue.q.vals)]
  Colombia.red.vals=Colombia.red.q.vals[(length(Colombia.red.q.vals)-3):length(Colombia.red.q.vals)]
  
  B.blue.labels=paste0(Brazil.signif.blues[(length(Brazil.blue.q.vals)-3):length(Brazil.blue.q.vals)]," (q = ",signif(Brazil.blue.q.vals,digits=2)[(length(Brazil.blue.q.vals)-3):length(Brazil.blue.q.vals)]*100,"%)")
  B.red.labels=paste0(Brazil.signif.reds[(length(Brazil.blue.q.vals)-3):length(Brazil.blue.q.vals)]," (q = ",signif(Brazil.red.q.vals,digits=2)[(length(Brazil.red.q.vals)-3):length(Brazil.red.q.vals)]*100,"%)")
  C.blue.labels=paste0(Colombia.signif.blues[(length(Colombia.blue.q.vals)-3):length(Colombia.blue.q.vals)]," (q = ",signif(Colombia.blue.q.vals,digits=2)[(length(Colombia.blue.q.vals)-3):length(Colombia.blue.q.vals)]*100,"%)")
  C.red.labels=paste0(Colombia.signif.reds[(length(Colombia.blue.q.vals)-3):length(Colombia.blue.q.vals)]," (q = ",signif(Colombia.red.q.vals,digits=2)[(length(Colombia.red.q.vals)-3):length(Colombia.red.q.vals)]*100,"%)")
  
  B.blue.labels[which(Brazil.blue.vals > .99 & Brazil.blue.vals < 1)]=
    paste0(substr(B.blue.labels[which(Brazil.blue.vals > .99 & Brazil.blue.vals < 1)],1,3),"(q > 99%)")
  B.red.labels[which(Brazil.red.vals > .99 & Brazil.red.vals < 1)]=
    paste0(substr(B.red.labels[which(Brazil.red.vals > .99 & Brazil.red.vals < 1)],1,3),"(q > 99%)")
  C.blue.labels[which(Colombia.blue.vals > .99 & Colombia.blue.vals < 1)]=
    paste0(substr(C.blue.labels[which(Colombia.blue.vals > .99 & Colombia.blue.vals < 1)],1,3),"(q > 99%)")
  C.red.labels[which(Colombia.red.vals > .99 & Colombia.red.vals < 1)]=
    paste0(substr( C.red.labels[which(Colombia.red.vals > .99 & Colombia.red.vals < 1)],1,3),"(q > 99%)")
}

rbind(Brazil.blue.q.vals,Brazil.blue.q2.vals
      ,Brazil.red.q.vals,Brazil.red.q2.vals)
rbind(Colombia.blue.q.vals,Colombia.blue.q2.vals
      ,Colombia.red.q.vals,Colombia.red.q2.vals)     

max(abs(Colombia.blue.q.vals-Colombia.blue.q2.vals))
max(abs(Colombia.red.q.vals-Colombia.red.q2.vals))
max(abs(Brazil.blue.q.vals-Brazil.blue.q2.vals))
max(abs(Brazil.red.q.vals-Brazil.red.q2.vals))

median(median(abs(Colombia.blue.q.vals-Colombia.blue.q2.vals)),
median(abs(Colombia.red.q.vals-Colombia.red.q2.vals)),
median(abs(Brazil.blue.q.vals-Brazil.blue.q2.vals)),
median(abs(Brazil.red.q.vals-Brazil.red.q2.vals)))


## Figure 2
redblue.plot=ggplot(m, aes(x=as.Date(biweekEndDate), y=pindex))+
  geom_tile(fill=m$test.colors)+ 
  xlab("")+   #"Date (biweeks)"
  scale_y_continuous(
    breaks=unique(m$pindex) #unique(m$pindex[which(m$pindex<0)])
    , labels = c("",""
                 ,unique(attBrazil$getActualName(Brazil.m$location))[-1]
                 ,"",""
                 ,unique(attColombia$getActualName(Colombia.m$location))[-1])
    ,limits=c(-71,9.5)# Brazil and Colombia  #,limits=c(min(m$pindex)-3.5,max(m$pindex)+7)
 #   ,limits=c(-27.5,9.5)# Brazil only
 #   ,limits=c(-68.5,-27.5)# Colombia only
    ,expand=c(0,0)
    ,position="right" #
  )+
  theme_linedraw()+
  theme(
    panel.border = element_blank()
  #  ,panel.grid.major = element_blank()
  #  ,panel.grid.major = element_line(size=0.25) #
    ,panel.grid.major.y = element_blank()
    ,panel.grid.minor = element_blank()
    ,axis.title.y = element_blank()
    ,axis.ticks.y=element_blank()
    ,axis.text=element_text(size=6)
  ,axis.text.y=element_text(angle=35)# element_blank()
    ,axis.text.x=element_text(hjust=-0.5,vjust=-2)
    ,axis.ticks.x=element_blank()
    #     ,axis.ticks.length=unit(.5, "cm")
    #      ,axis.ticks=element_line(size=0.7)
  )

redblue.plot+
  scale_x_date(
    "" #Date (biweeks)
    ,limits= c(start.x,end.x)
    ,breaks=temp.breaks
    ,labels=rep("",length(temp.breaks))
    ,expand=c(0,0)
  )+
  guides(alpha=F)+

  # horizontal lines
  geom_segment(x=start.x,xend=end.x,y=start.y,yend=start.y)+ geom_segment(x=start.x,xend=end.x,y=end.y,yend=end.y)+
  geom_segment(x=start.x,xend=end.x,y=y1,yend=y1)+ geom_segment(x=start.x,xend=end.x,y=y1-2.5,yend=y1-2.5)+
  geom_segment(x=start.x,xend=end.x,y=y2,yend=y2)+
  geom_segment(x=start.x,xend=end.x,y=9.5,yend=9.5)+geom_segment(x=start.x,xend=end.x,y=7,yend=7)+
  geom_segment(x=start.x,xend=end.x,y=end.y-2.5,yend=end.y-2.5)+
  
  # vertical lines
  geom_segment(x=start.x,xend=start.x,y=-71,yend=9.5)+ 
  geom_segment(x=start.x+365,xend=start.x+365,y=-71,yend=9.5)+# geom_segment(x=end.x,xend=end.x,y=-71,yend=9.5)+
  geom_segment(x=temp.breaks[3],xend=temp.breaks[3],y=-71,yend=9.5)+
  geom_segment(x=temp.breaks[4],xend=temp.breaks[4],y=-71,yend=9.5)+
  geom_segment(x=end.x,xend=end.x,y=-71,yend=9.5)+
  
  
  annotate("text",label=label.years,x=x.year,y=8.25,size=2)+
  annotate("text",label=label.years,x=x.year,y=y1-1.25,size=2)+
  annotate("text",label=label.years,x=x.year,y=min(m$pindex)-1.5,size=2)+
  annotate("text",label=B.red.labels,x=x.year[1:4],y=6,col="red",size=2)+ #,size=4
  annotate("text",label=B.blue.labels,x=x.year[1:4],y=1,col="blue",size=2)+
  annotate("text",label=C.red.labels,x=x.year[1:4],y=-31,col="red",size=2)+
  annotate("text",label=C.blue.labels,x=x.year[1:4],y=-36,col="blue",size=2)+

  theme(
    plot.margin=unit(c(0.1,0,-0.7,0.25),'cm')
  )

## SI Figure 5 and 6: full red/blue plots
## fill=m$test.colors for SI Figure 5 
## fill=m$test.colors.adjust for SI Figure 6 (Bonferroni corrected values)

m=temp.full.m

top.line=1.5
bottom.line=min(temp.full.m$pindex)-0.5

# get date boundaries and labels
time.start=min(as.Date(m$biweekEndDate))
time.end=max(as.Date(m$biweekEndDate))+7

start.x = as.Date(time.start-8)
end.x = as.Date(time.end+1)
start.y = max(m$pindex[which(m$pindex <0)] )+0.5
end.y = min(m$pindex)-0.5

start.x2=start.x+7*365

# these breaks are most appropriate for recent years only plots 
# since forcing 26 biweeks in each year for model pushes some biweeks into adjacent years
temp.breaks=c()
for(temp.year in unique(m$year)){
  temp.dat=subset(m,year==temp.year)
  temp.breaks=c(temp.breaks,as.character(temp.dat$biweekEndDate[1]))
}
temp.breaks=as.Date(temp.breaks)-7
label.years=as.integer(substr(as.character(temp.breaks), 1,4))
temp.breaks=c(temp.breaks,time.end)
label.years=c(label.years,"")
label.years2=c(rep("",7),2007:2017,"")
x.year=temp.breaks+365/2


y1=unique(subset(m,location=="Rio_Grande_do_Sul")$pindex)-0.5
y2=unique(subset(m,location=="San_Andres")$pindex)+0.5

redblue.plot=ggplot(m, aes(x=as.Date(biweekEndDate), y=pindex))+
  geom_tile(fill=m$test.colors.adjust)+ #.adjust
  xlab("")+   #"Date (biweeks)"
  scale_y_continuous(
    breaks=unique(m$pindex) #unique(m$pindex[which(m$pindex<0)])
    , labels = c(unique(attBrazil$getActualName(Brazil.m$location))[-1]
                 ,unique(attColombia$getActualName(Colombia.m$location))[-1])
    ,limits=c(bottom.line,top.line)# Brazil and Colombia  #,limits=c(min(m$pindex)-3.5,max(m$pindex)+7)
    ,expand=c(0,0)
    ,position="right" #
  )+
  theme_linedraw()+
  theme(
    panel.border = element_blank()
    #  ,panel.grid.major = element_blank()
    #  ,panel.grid.major = element_line(size=0.25) #
    ,panel.grid.major.y = element_blank()
    ,panel.grid.minor = element_blank()
    ,axis.title.y = element_blank()
    ,axis.ticks.y=element_blank()
    ,axis.text=element_text(size=6)
    ,axis.text.y=element_text(angle=35)# element_blank()
    ,axis.text.x=element_text(hjust=-0.5,vjust=-2)
    ,axis.ticks.x=element_blank()
    #     ,axis.ticks.length=unit(.5, "cm")
    #      ,axis.ticks=element_line(size=0.7)
  )



redblue.plot+
  scale_x_date(
    "" #Date (biweeks)
    ,limits= c(start.x,end.x)
    ,breaks=temp.breaks
    ,labels=rep("",length(temp.breaks))
    ,expand=c(0,0)
  )+
  guides(alpha=F)+
  
  # horizontal lines
  geom_segment(x=start.x,xend=end.x,y=start.y,yend=start.y)+
  geom_segment(x=start.x,xend=end.x,y=y1,yend=y1)+ 
  geom_segment(x=start.x2,xend=end.x,y=y2,yend=y2)+ 
  geom_segment(x=start.x2,xend=end.x,y=y2+2,yend=y2+2)+
  geom_segment(x=start.x,xend=end.x,y=top.line,yend=top.line)+
  geom_segment(x=start.x2,xend=end.x,y=end.y,yend=end.y)+
  #  geom_segment(x=start.x,xend=end.x,y=end.y-2.5,yend=end.y-2.5)+
  
  # # vertical lines
  geom_segment(x=start.x,xend=start.x,y=y1,yend=top.line)+ 
  geom_segment(x=start.x2,xend=start.x2,y=bottom.line,yend=y2+2)+ 
  geom_segment(x=end.x,xend=end.x,y=y1,yend=top.line)+
  geom_segment(x=end.x,xend=end.x,y=bottom.line,yend=y2+2)+
   
  annotate("text",label=label.years,x=x.year,y=top.line-1,size=2)+
  annotate("text",label=label.years2,x=x.year,y=y2+1,size=2)+
 # annotate("text",label=label.years,x=x.year,y=min(m$pindex)-1.5,size=2)+
  theme(
    plot.margin=unit(c(0.1,0,-0.7,0.25),'cm')
  )




## Predicted vs. observed dengue incidence plots
## SI Figure 4

Brazil.plot = ggplot(data=Brazil.full.m %>% filter(year<2015) ,mapping=aes( #
  x = log10(observed)
  ,y = log10(median.pred)
))+geom_point(size=2,alpha =0.2)+
  geom_abline(slope=1,intercept=c(0,0))+
  theme(
    panel.border = element_blank()
  )+
  xlab("")+  # xlab("Observed dengue cases")+  
  ylab("")+ #ylab("Median predicted dengue cases")+
  scale_y_continuous(
    limits=c(0,5)
    , breaks=c(0,1,2,3,4,5)
    , labels = c(1,10,100,1000,10000,100000)
  )+
  scale_x_continuous(
    limits=c(0,5)
    , breaks=c(0,1,2,3,4,5)
    , labels = c(1,10,100,1000,10000,100000)
  )+
  coord_fixed()+
  ggtitle("Brazil")+
  theme_bw(base_size = 14)


Colombia.plot = ggplot(data=Colombia.full.m %>% filter(year<2015),mapping=aes(
  x = log10(observed)
  ,y = log10(median.pred)
))+geom_point(size=2,alpha =0.2)+
  geom_abline(slope=1,intercept=c(0,0))+
  theme(
    panel.border = element_blank()
  )+
  xlab("Observed dengue cases")+  
  ylab("Median predicted dengue cases")+
  scale_y_continuous(
    breaks=c(0,1,2,3,4)
    , labels = c(1,10,100,1000,10000)
  )+
  scale_x_continuous(
    breaks=c(0,1,2,3,4)
    , labels = c(1,10,100,1000,10000)
  )+
  coord_fixed()+
  ggtitle("Colombia")+
  theme_bw(base_size = 14)

Colombia.plot.expand = ggplot(data=Colombia.full.m %>% filter(year<2015),mapping=aes(
  x = log10(observed)
  ,y = log10(median.pred)
))+geom_point(size=2,alpha =0.2)+
  geom_abline(slope=1,intercept=c(0,0))+
  theme(
    panel.border = element_blank()
  )+
  xlab("")+  
  ylab("")+
  scale_y_continuous(
    limits=c(0,5)
    , breaks=c(0,1,2,3,4,5)
    , labels = c(1,10,100,1000,10000,100000)
  )+
  scale_x_continuous(
    limits=c(0,5)
    , breaks=c(0,1,2,3,4,5)
    , labels = c(1,10,100,1000,10000,100000)
  )+
  coord_fixed()+
  ggtitle("Colombia")+
  theme_bw(base_size = 14)


grid.arrange(Brazil.plot, Colombia.plot.expand, ncol=2
             , bottom=textGrob("Observed dengue cases", gp=gpar(fontsize=16))
             , left = textGrob("Median predicted dengue cases",gp=gpar(fontsize=16),rot=90))
